# Generated by Django 2.1.7 on 2019-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20190404_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
