# Generated by Django 2.1.7 on 2019-04-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='streamkey',
            field=models.CharField(default='nztFBAAKGszl0N0qhCa0', max_length=20),
        ),
    ]
