# Generated by Django 2.1.7 on 2019-04-03 07:50

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190403_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='streamkey',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(20,), **{}), max_length=20),
        ),
    ]
